
name: appoptics-digitalocean-node
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eristoddle/appoptics-digitalocean-node
  name: appoptics-digitalocean-node